name: Prettier
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  prettier:
    name: Prettify code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: creyD/prettier_action@v2.2
        with:
          prettier_options: --write **/*
